CREATE USER IF NOT EXISTS 'manufacturing'@'localhost' IDENTIFIED BY 'kimngan1704';

-- GRANT CREATE ON manufacturing.* TO 'roy'@'localhost';
CREATE USER `roy`@`localhost` IDENTIFIED BY '123456' ;
GRANT ALL PRIVILEGES ON manufacturing.* TO 'roy'@'localhost';
-- GRANT ALL PRIVILEGES ON *.* TO 'roy'@'localhost'; roy is root
-- GRANT ALL PRIVILEGES ON database_name.* TO 'username'@'localhost'
FLUSH PRIVILEGES;


alter user 'root'@'localhost' identified with mysql_native_password by 'kimngan1704';
-- alter user 'roy'@'localhost' identified with mysql_native_password by 'kimngan1704';
-- alter user 'son.buidai@gmail.com'@'localhost' identified with mysql_native_password by '123456';




/* EmployeeType:
    1: Analyst
    2: Manager
    3: Worker
    4: Designer
    5: Others */
use manufacturing;
DROP VIEW IF EXISTS EmployeeView;
CREATE VIEW EmployeeView AS
SELECT ID, SSN, FName, MName, LName, BDate, Address, Salary, EmployeeType
FROM Employee
WITH LOCAL CHECK OPTION;

/*DROP VIEW IF EXISTS ManagerView;
CREATE VIEW ManagerView AS
SELECT ID, SSN, FName, MName, LName, BDate, Address, Salary, EmployeeType
FROM Employee WHERE EmployeeType = 2
WITH LOCAL CHECK OPTION;

DROP VIEW IF EXISTS WorkerView;
CREATE VIEW WorkerView AS
SELECT ID, SSN, FName, MName, LName, BDate, Address, Salary, EmployeeType
FROM Employee WHERE EmployeeType = 3
WITH LOCAL CHECK OPTION;

DROP VIEW IF EXISTS DesignerView;
CREATE VIEW DesignerView AS
SELECT ID, SSN, FName, MName, LName, BDate, Address, Salary, EmployeeType
FROM Employee WHERE EmployeeType = 4
WITH LOCAL CHECK OPTION;*/

DROP VIEW IF EXISTS ProjectView;
CREATE VIEW ProjectView AS
SELECT PID, Name, Description, CostEfficiency, Cost, ID, StartDate, Period
FROM Project
WITH LOCAL CHECK OPTION;

DROP VIEW IF EXISTS ProductView;
CREATE VIEW ProductView AS
SELECT PID
FROM Product
WITH LOCAL CHECK OPTION;

DROP VIEW IF EXISTS ActivityView;
CREATE VIEW ActivityView AS
SELECT AID
FROM Activity
WITH LOCAL CHECK OPTION;

DROP VIEW IF EXISTS ModelView;
CREATE VIEW ModelView AS
SELECT MNumber, PID, ID, DateCreated
FROM Model
WITH LOCAL CHECK OPTION;

DROP VIEW IF EXISTS EquipmentView;
CREATE VIEW EquipmentView AS
SELECT PID
FROM Equipment
WITH LOCAL CHECK OPTION;

DROP VIEW IF EXISTS NotificationView;
CREATE VIEW NotificationView AS
SELECT NID, PID
FROM Notification
WITH LOCAL CHECK OPTION;



drop role if exists `ManagerRole`@`localhost`;
CREATE ROLE `ManagerRole`@`localhost`;

GRANT SELECT, INSERT, UPDATE, DELETE ON MANUFACTURING.ProjectView TO `ManagerRole`@`localhost`;
GRANT SELECT, INSERT, UPDATE, DELETE ON MANUFACTURING.EmployeeView TO `ManagerRole`@`localhost`;
GRANT SELECT, INSERT, UPDATE, DELETE ON MANUFACTURING.ProductView TO `ManagerRole`@`localhost`;
GRANT SELECT, INSERT, UPDATE, DELETE ON MANUFACTURING.ModelView TO `ManagerRole`@`localhost`;
GRANT SELECT, INSERT, UPDATE, DELETE ON MANUFACTURING.EquipmentView TO `ManagerRole`@`localhost`;
GRANT SELECT, INSERT, UPDATE, DELETE ON MANUFACTURING.ActivityView TO `ManagerRole`@`localhost`;
GRANT SELECT, INSERT, UPDATE, DELETE ON MANUFACTURING.NotificationView TO `ManagerRole`@`localhost`;

drop role if exists `WorkerRole`@`localhost`;
CREATE ROLE `WorkerRole`@`localhost`;
GRANT SELECT ON manufacturing.Equipment TO `WorkerRole`@`localhost`;
GRANT SELECT ON MANUFACTURING.Notification TO `WorkerRole`@`localhost`;
GRANT SELECT ON MANUFACTURING.Product TO `WorkerRole`@`localhost`;


drop role if exists `DesignerRole`@`localhost`;
CREATE ROLE `DesignerRole`@`localhost`;
GRANT SELECT ON MANUFACTURING.ModelView TO `DesignerRole`@`localhost`;
GRANT SELECT ON MANUFACTURING.Product TO `DesignerRole`@`localhost`;

flush privileges;

-- create manager role
CREATE USER `minh.buikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `ManagerRole`@`localhost` TO `minh.buikim@gmail.com`@`localhost` ;
CREATE USER `thu.buithi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `ManagerRole`@`localhost` TO `thu.buithi@gmail.com`@`localhost` ;
-- CREATE USER `anh.buituan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `anh.buituan@gmail.com`@`localhost` ;
-- CREATE USER `thanh.buixuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `thanh.buixuan@gmail.com`@`localhost` ;
-- CREATE USER `hien.caophamthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hien.caophamthanh@gmail.com`@`localhost` ;
-- CREATE USER `ngan.caothihai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ngan.caothihai@gmail.com`@`localhost` ;
-- CREATE USER `guan.chaiyeong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `guan.chaiyeong@gmail.com`@`localhost` ;
-- CREATE USER `thanh.chaudai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `thanh.chaudai@gmail.com`@`localhost` ;
-- CREATE USER `truc.danghoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `truc.danghoang@gmail.com`@`localhost` ;
-- CREATE USER `hanh.dangthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hanh.dangthimy@gmail.com`@`localhost` ;
-- CREATE USER `du.daocao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `du.daocao@gmail.com`@`localhost` ;
-- CREATE USER `hai.daothien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hai.daothien@gmail.com`@`localhost` ;
-- CREATE USER `phong.dinhtran@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `phong.dinhtran@gmail.com`@`localhost` ;
-- CREATE USER `nam.dohoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `nam.dohoang@gmail.com`@`localhost` ;
-- CREATE USER `nguyen.dongocthao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `nguyen.dongocthao@gmail.com`@`localhost` ;
-- CREATE USER `khuyen.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `khuyen.dothi@gmail.com`@`localhost` ;
-- CREATE USER `ngan.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ngan.dothi@gmail.com`@`localhost` ;
-- CREATE USER `van.doanthituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `van.doanthituyet@gmail.com`@`localhost` ;
-- CREATE USER `truong.doanxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `truong.doanxuan@gmail.com`@`localhost` ;
-- CREATE USER `cuong.duongquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `cuong.duongquoc@gmail.com`@`localhost` ;
-- CREATE USER `thuan.hodang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `thuan.hodang@gmail.com`@`localhost` ;
-- CREATE USER `hao.hohuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hao.hohuu@gmail.com`@`localhost` ;
-- CREATE USER `thanh.hothithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `thanh.hothithu@gmail.com`@`localhost` ;
-- CREATE USER `trinh.hoangnukieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `trinh.hoangnukieu@gmail.com`@`localhost` ;
-- CREATE USER `anh.hoangquynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `anh.hoangquynh@gmail.com`@`localhost` ;
-- CREATE USER `tung.hoangthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `tung.hoangthanh@gmail.com`@`localhost` ;
-- CREATE USER `sinh.huadieptruong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `sinh.huadieptruong@gmail.com`@`localhost` ;
-- CREATE USER `tat.huynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `tat.huynh@gmail.com`@`localhost` ;
-- CREATE USER `nghia.huynhngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `nghia.huynhngoc@gmail.com`@`localhost` ;
-- CREATE USER `hung.huynhnhat@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hung.huynhnhat@gmail.com`@`localhost` ;
-- CREATE USER `sac.huynhtang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `sac.huynhtang@gmail.com`@`localhost` ;
-- CREATE USER `dung.huynhthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `dung.huynhthanh@gmail.com`@`localhost` ;
-- CREATE USER `diep.huynhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `diep.huynhthi@gmail.com`@`localhost` ;
-- CREATE USER `nga.huynhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `nga.huynhthi@gmail.com`@`localhost` ;
-- CREATE USER `to.huynhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `to.huynhthi@gmail.com`@`localhost` ;
-- CREATE USER `thuy.huynhthicam@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `thuy.huynhthicam@gmail.com`@`localhost` ;
-- CREATE USER `lan.huynhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `lan.huynhvan@gmail.com`@`localhost` ;
-- CREATE USER `minh.huynhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `minh.huynhvan@gmail.com`@`localhost` ;
-- CREATE USER `trang.khauthiyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `trang.khauthiyen@gmail.com`@`localhost` ;
-- CREATE USER `tuyet.lamnhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `tuyet.lamnhu@gmail.com`@`localhost` ;
-- CREATE USER `phuong.lemy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `phuong.lemy@gmail.com`@`localhost` ;
-- CREATE USER `danh.lethanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `danh.lethanh@gmail.com`@`localhost` ;
-- CREATE USER `ty.lethihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ty.lethihong@gmail.com`@`localhost` ;
-- CREATE USER `hoa.luongthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hoa.luongthi@gmail.com`@`localhost` ;
-- CREATE USER `dung.lyanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `dung.lyanh@gmail.com`@`localhost` ;
-- CREATE USER `lam.lyson@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `lam.lyson@gmail.com`@`localhost` ;
-- CREATE USER `koko.mady@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `koko.mady@gmail.com`@`localhost` ;
-- CREATE USER `nguyen.ngohuynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `nguyen.ngohuynh@gmail.com`@`localhost` ;
-- CREATE USER `dung.ngoquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `dung.ngoquang@gmail.com`@`localhost` ;
-- CREATE USER `vinh.ngothe@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `vinh.ngothe@gmail.com`@`localhost` ;
-- CREATE USER `trong.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `trong.nguyen@gmail.com`@`localhost` ;
-- CREATE USER `ninh.nguyendoan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ninh.nguyendoan@gmail.com`@`localhost` ;
-- CREATE USER `duong.nguyenduc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `duong.nguyenduc@gmail.com`@`localhost` ;
-- CREATE USER `uyen.nguyengiamai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `uyen.nguyengiamai@gmail.com`@`localhost` ;
-- CREATE USER `duy.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `duy.nguyenhoang@gmail.com`@`localhost` ;
-- CREATE USER `nam.nguyenhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `nam.nguyenhong@gmail.com`@`localhost` ;
-- CREATE USER `cuong.nguyenhung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `cuong.nguyenhung@gmail.com`@`localhost` ;
-- CREATE USER `ngan.nguyenkim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ngan.nguyenkim@gmail.com`@`localhost` ;
-- CREATE USER `hunh.nguyenmanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hunh.nguyenmanh@gmail.com`@`localhost` ;
-- CREATE USER `duc.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `duc.nguyenminh@gmail.com`@`localhost` ;
-- CREATE USER `quang.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `quang.nguyenminh@gmail.com`@`localhost` ;
-- CREATE USER `thuan.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `thuan.nguyenminh@gmail.com`@`localhost` ;
-- CREATE USER `thuc.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `thuc.nguyenminh@gmail.com`@`localhost` ;
-- CREATE USER `hoa.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hoa.nguyenngoc@gmail.com`@`localhost` ;
-- CREATE USER `qui.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `qui.nguyenngoc@gmail.com`@`localhost` ;
-- CREATE USER `long.nguyenphi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `long.nguyenphi@gmail.com`@`localhost` ;
-- CREATE USER `thao.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `thao.nguyenthanh@gmail.com`@`localhost` ;
-- CREATE USER `tung.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `tung.nguyenthanh@gmail.com`@`localhost` ;
-- CREATE USER `long.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `long.nguyenthanh@gmail.com`@`localhost` ;
-- CREATE USER `dung.nguyenthe@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `dung.nguyenthe@gmail.com`@`localhost` ;
-- CREATE USER `an.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `an.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `diem.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `diem.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `ha.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ha.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `linh.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `linh.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `luan.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `luan.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `man.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `man.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `nguyet.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `nguyet.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `oanh.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `oanh.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `thuy.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `thuy.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `dao.nguyenthianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `dao.nguyenthianh@gmail.com`@`localhost` ;
-- CREATE USER `hoa.nguyenthicong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hoa.nguyenthicong@gmail.com`@`localhost` ;
-- CREATE USER `dieu.nguyenthihanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `dieu.nguyenthihanh@gmail.com`@`localhost` ;
-- CREATE USER `ly.nguyenthihoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ly.nguyenthihoai@gmail.com`@`localhost` ;
-- CREATE USER `huong.nguyenthihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `huong.nguyenthihoang@gmail.com`@`localhost` ;
-- CREATE USER `dung.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `dung.nguyenthikim@gmail.com`@`localhost` ;
-- CREATE USER `phuong.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `phuong.nguyenthikim@gmail.com`@`localhost` ;
-- CREATE USER `oanh.nguyenthile@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `oanh.nguyenthile@gmail.com`@`localhost` ;
-- CREATE USER `ly.nguyenthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ly.nguyenthimy@gmail.com`@`localhost` ;
-- CREATE USER `bang.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `bang.nguyenthingoc@gmail.com`@`localhost` ;
-- CREATE USER `em.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `em.nguyenthingoc@gmail.com`@`localhost` ;
-- CREATE USER `tuyet.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `tuyet.nguyenthingoc@gmail.com`@`localhost` ;
-- CREATE USER `hien.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hien.nguyenthithu@gmail.com`@`localhost` ;
-- CREATE USER `thao.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `thao.nguyenthithu@gmail.com`@`localhost` ;
-- CREATE USER `trang.nguyenthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `trang.nguyenthithuy@gmail.com`@`localhost` ;
-- CREATE USER `mai.nguyenthituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `mai.nguyenthituyet@gmail.com`@`localhost` ;
-- CREATE USER `hien.nguyenthuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hien.nguyenthuong@gmail.com`@`localhost` ;
-- CREATE USER `lam.nguyentung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `lam.nguyentung@gmail.com`@`localhost` ;
-- CREATE USER `vy.nguyentuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `vy.nguyentuong@gmail.com`@`localhost` ;
-- CREATE USER `bay.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `bay.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `cam.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `cam.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `canh.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `canh.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `ha.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ha.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `hien.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hien.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `tan.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `tan.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `tho.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `tho.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `tien.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `tien.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `cuong.nguyenviet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `cuong.nguyenviet@gmail.com`@`localhost` ;
-- CREATE USER `hieu.nuyenthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hieu.nuyenthihong@gmail.com`@`localhost` ;
-- CREATE USER `vuong.pham@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `vuong.pham@gmail.com`@`localhost` ;
-- CREATE USER `phong.phamduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `phong.phamduy@gmail.com`@`localhost` ;
-- CREATE USER `linh.phamhoaikhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `linh.phamhoaikhanh@gmail.com`@`localhost` ;
-- CREATE USER `khanh.phamhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `khanh.phamhong@gmail.com`@`localhost` ;
-- CREATE USER `khoi.phammanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `khoi.phammanh@gmail.com`@`localhost` ;
-- CREATE USER `son.phamngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `son.phamngoc@gmail.com`@`localhost` ;
-- CREATE USER `luat.phamquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `luat.phamquang@gmail.com`@`localhost` ;
-- CREATE USER `oanh.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `oanh.phamthi@gmail.com`@`localhost` ;
-- CREATE USER `xuan.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `xuan.phamthi@gmail.com`@`localhost` ;
-- CREATE USER `loan.phamthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `loan.phamthihong@gmail.com`@`localhost` ;
-- CREATE USER `hanh.phamthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hanh.phamthithu@gmail.com`@`localhost` ;
-- CREATE USER `loan.phamthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `loan.phamthithu@gmail.com`@`localhost` ;
-- CREATE USER `dao.phamthitruc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `dao.phamthitruc@gmail.com`@`localhost` ;
-- CREATE USER `anh.phanhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `anh.phanhoang@gmail.com`@`localhost` ;
-- CREATE USER `phong.phanthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `phong.phanthithu@gmail.com`@`localhost` ;
-- CREATE USER `hau.phantrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hau.phantrung@gmail.com`@`localhost` ;
-- CREATE USER `hieu.phanvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hieu.phanvan@gmail.com`@`localhost` ;
-- CREATE USER `long.phunghoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `long.phunghoang@gmail.com`@`localhost` ;
-- CREATE USER `nguyen.phuongcao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `nguyen.phuongcao@gmail.com`@`localhost` ;
-- CREATE USER `trang.tannhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `trang.tannhu@gmail.com`@`localhost` ;
-- CREATE USER `hue.tongthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hue.tongthi@gmail.com`@`localhost` ;
-- CREATE USER `ngoc.tranbao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ngoc.tranbao@gmail.com`@`localhost` ;
-- CREATE USER `sang.tranbao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `sang.tranbao@gmail.com`@`localhost` ;
-- CREATE USER `hung.trancong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hung.trancong@gmail.com`@`localhost` ;
-- CREATE USER `chien.trandinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `chien.trandinh@gmail.com`@`localhost` ;
-- CREATE USER `duong.trandinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `duong.trandinh@gmail.com`@`localhost` ;
-- CREATE USER `tri.tranhuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `tri.tranhuu@gmail.com`@`localhost` ;
-- CREATE USER `vuong.trankim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `vuong.trankim@gmail.com`@`localhost` ;
-- CREATE USER `ngan.tranngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ngan.tranngoc@gmail.com`@`localhost` ;
-- CREATE USER `van.trannhat@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `van.trannhat@gmail.com`@`localhost` ;
-- CREATE USER `triet.tranongminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `triet.tranongminh@gmail.com`@`localhost` ;
-- CREATE USER `ha.tranphamthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `ha.tranphamthanh@gmail.com`@`localhost` ;
-- CREATE USER `linh.tranquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `linh.tranquoc@gmail.com`@`localhost` ;
-- CREATE USER `bup.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `bup.tranthi@gmail.com`@`localhost` ;
-- CREATE USER `hien.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hien.tranthi@gmail.com`@`localhost` ;
-- CREATE USER `thu.tranthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `thu.tranthihong@gmail.com`@`localhost` ;
-- CREATE USER `hoa.tranthoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `hoa.tranthoai@gmail.com`@`localhost` ;
-- CREATE USER `anh.trantuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `anh.trantuan@gmail.com`@`localhost` ;
-- CREATE USER `nhat.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `nhat.tranvan@gmail.com`@`localhost` ;
-- CREATE USER `that.truongthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `that.truongthi@gmail.com`@`localhost` ;
-- CREATE USER `dung.truongtien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `ManagerRole`@`localhost` TO `dung.truongtien@gmail.com`@`localhost` ;

-- create worker account

CREATE USER `son.buidai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `WorkerRole`@`localhost` TO `son.buidai@gmail.com`@`localhost` ;
CREATE USER `nam.buithihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `WorkerRole`@`localhost` TO `nam.buithihong@gmail.com`@`localhost` ;
-- CREATE USER `duong.buithithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `duong.buithithuy@gmail.com`@`localhost` ;
-- CREATE USER `mai.buithitruc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `mai.buithitruc@gmail.com`@`localhost` ;
-- CREATE USER `trinh.buithituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `trinh.buithituyet@gmail.com`@`localhost` ;
-- CREATE USER `ky.buitrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ky.buitrung@gmail.com`@`localhost` ;
-- CREATE USER `kiet.buituan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `kiet.buituan@gmail.com`@`localhost` ;
-- CREATE USER `hien.buivan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hien.buivan@gmail.com`@`localhost` ;
-- CREATE USER `phuong.chau@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `phuong.chau@gmail.com`@`localhost` ;
-- CREATE USER `ha.chaudai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ha.chaudai@gmail.com`@`localhost` ;
-- CREATE USER `son.chaudai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `son.chaudai@gmail.com`@`localhost` ;
-- CREATE USER `hau.cungtrong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hau.cungtrong@gmail.com`@`localhost` ;
-- CREATE USER `tuan.dangmai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tuan.dangmai@gmail.com`@`localhost` ;
-- CREATE USER `tuyen.dangthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tuyen.dangthanh@gmail.com`@`localhost` ;
-- CREATE USER `vvan.dangthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `vvan.dangthithanh@gmail.com`@`localhost` ;
-- CREATE USER `ngoc.daoxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ngoc.daoxuan@gmail.com`@`localhost` ;
-- CREATE USER `dang.dodinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `dang.dodinh@gmail.com`@`localhost` ;
-- CREATE USER `hai.dominh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hai.dominh@gmail.com`@`localhost` ;
-- CREATE USER `trung.duongthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `trung.duongthanh@gmail.com`@`localhost` ;
-- CREATE USER `tuong.hathanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tuong.hathanh@gmail.com`@`localhost` ;
-- CREATE USER `huyen.hathi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `huyen.hathi@gmail.com`@`localhost` ;
-- CREATE USER `kieu.hathimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `kieu.hathimy@gmail.com`@`localhost` ;
-- CREATE USER `toan.hoanghai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `toan.hoanghai@gmail.com`@`localhost` ;
-- CREATE USER `lien.hoangthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `lien.hoangthi@gmail.com`@`localhost` ;
-- CREATE USER `thuy.hoangthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thuy.hoangthi@gmail.com`@`localhost` ;
-- CREATE USER `dung.hoangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `dung.hoangvan@gmail.com`@`localhost` ;
-- CREATE USER `manh.hoangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `manh.hoangvan@gmail.com`@`localhost` ;
-- CREATE USER `tam.huynhhuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tam.huynhhuu@gmail.com`@`localhost` ;
-- CREATE USER `tuan.huynhthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tuan.huynhthanh@gmail.com`@`localhost` ;
-- CREATE USER `tram.huynhthihuyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tram.huynhthihuyen@gmail.com`@`localhost` ;
-- CREATE USER `tho.huynhthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tho.huynhthikim@gmail.com`@`localhost` ;
-- CREATE USER `trinh.kieuthihuyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `trinh.kieuthihuyen@gmail.com`@`localhost` ;
-- CREATE USER `thu.laithianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thu.laithianh@gmail.com`@`localhost` ;
-- CREATE USER `kinh.lamdai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `kinh.lamdai@gmail.com`@`localhost` ;
-- CREATE USER `lieu.lanhthinhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `lieu.lanhthinhu@gmail.com`@`localhost` ;
-- CREATE USER `an.leduc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `an.leduc@gmail.com`@`localhost` ;
-- CREATE USER `hien.lehong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hien.lehong@gmail.com`@`localhost` ;
-- CREATE USER `su.lehong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `su.lehong@gmail.com`@`localhost` ;
-- CREATE USER `vi.lemoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `vi.lemoc@gmail.com`@`localhost` ;
-- CREATE USER `canh.lenguyenhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `canh.lenguyenhong@gmail.com`@`localhost` ;
-- CREATE USER `vinh.lethaihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `vinh.lethaihoang@gmail.com`@`localhost` ;
-- CREATE USER `thanh.lethi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thanh.lethi@gmail.com`@`localhost` ;
-- CREATE USER `ly.lethihai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ly.lethihai@gmail.com`@`localhost` ;
-- CREATE USER `tham.lethihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tham.lethihong@gmail.com`@`localhost` ;
-- CREATE USER `mo.lethituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `mo.lethituyet@gmail.com`@`localhost` ;
-- CREATE USER `chan.letranquynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `chan.letranquynh@gmail.com`@`localhost` ;
-- CREATE USER `thanh.letranthai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thanh.letranthai@gmail.com`@`localhost` ;
-- CREATE USER `binh.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `binh.levan@gmail.com`@`localhost` ;
-- CREATE USER `dung.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `dung.levan@gmail.com`@`localhost` ;
-- CREATE USER `sang.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `sang.levan@gmail.com`@`localhost` ;
-- CREATE USER `vang.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `vang.levan@gmail.com`@`localhost` ;
-- CREATE USER `trinh.luongduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `trinh.luongduy@gmail.com`@`localhost` ;
-- CREATE USER `nghiem.luuquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `nghiem.luuquoc@gmail.com`@`localhost` ;
-- CREATE USER `huong.maithi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `huong.maithi@gmail.com`@`localhost` ;
-- CREATE USER `cuc.ngothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `cuc.ngothi@gmail.com`@`localhost` ;
-- CREATE USER `vinh.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `vinh.nguyen@gmail.com`@`localhost` ;
-- CREATE USER `phan.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `phan.nguyen@gmail.com`@`localhost` ;
-- CREATE USER `khuong.nguyenanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `khuong.nguyenanh@gmail.com`@`localhost` ;
-- CREATE USER `linh.nguyenba@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `linh.nguyenba@gmail.com`@`localhost` ;
-- CREATE USER `ngoc.nguyenbao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ngoc.nguyenbao@gmail.com`@`localhost` ;
-- CREATE USER `dat.nguyenbientan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `dat.nguyenbientan@gmail.com`@`localhost` ;
-- CREATE USER `thanh.nguyenchi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thanh.nguyenchi@gmail.com`@`localhost` ;
-- CREATE USER `duc.nguyendac@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `duc.nguyendac@gmail.com`@`localhost` ;
-- CREATE USER `mong.nguyendinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `mong.nguyendinh@gmail.com`@`localhost` ;
-- CREATE USER `hung.nguyendoangia@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hung.nguyendoangia@gmail.com`@`localhost` ;
-- CREATE USER `phuc.nguyenduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `phuc.nguyenduy@gmail.com`@`localhost` ;
-- CREATE USER `thuy.nguyenhonhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thuy.nguyenhonhu@gmail.com`@`localhost` ;
-- CREATE USER `lac.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `lac.nguyenhoang@gmail.com`@`localhost` ;
-- CREATE USER `duan.nguyenlengoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `duan.nguyenlengoc@gmail.com`@`localhost` ;
-- CREATE USER `hieu.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hieu.nguyenngoc@gmail.com`@`localhost` ;
-- CREATE USER `hong.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hong.nguyenngoc@gmail.com`@`localhost` ;
-- CREATE USER `thuy.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thuy.nguyenngoc@gmail.com`@`localhost` ;
-- CREATE USER `ben.nguyenngocluc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ben.nguyenngocluc@gmail.com`@`localhost` ;
-- CREATE USER `huong.nguyenquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `huong.nguyenquang@gmail.com`@`localhost` ;
-- CREATE USER `khiem.nguyentan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `khiem.nguyentan@gmail.com`@`localhost` ;
-- CREATE USER `be.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `be.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `chi.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `chi.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `dung.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `dung.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `duong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `duong.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `hoang.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hoang.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `huong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `huong.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `lan.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `lan.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `ngoc.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ngoc.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `thuyen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thuyen.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `diep.nguyenthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `diep.nguyenthihong@gmail.com`@`localhost` ;
-- CREATE USER `anh.nguyenthilan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `anh.nguyenthilan@gmail.com`@`localhost` ;
-- CREATE USER `truc.nguyenthimong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `truc.nguyenthimong@gmail.com`@`localhost` ;
-- CREATE USER `han.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `han.nguyenthingoc@gmail.com`@`localhost` ;
-- CREATE USER `thuy.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thuy.nguyenthingoc@gmail.com`@`localhost` ;
-- CREATE USER `yen.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `yen.nguyenthingoc@gmail.com`@`localhost` ;
-- CREATE USER `linh.nguyenthiphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `linh.nguyenthiphuong@gmail.com`@`localhost` ;
-- CREATE USER `nga.nguyenthiphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `nga.nguyenthiphuong@gmail.com`@`localhost` ;
-- CREATE USER `thuy.nguyenthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thuy.nguyenthithanh@gmail.com`@`localhost` ;
-- CREATE USER `ha.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ha.nguyenthithu@gmail.com`@`localhost` ;
-- CREATE USER `lien.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `lien.nguyenthithu@gmail.com`@`localhost` ;
-- CREATE USER `thuy.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thuy.nguyenthithu@gmail.com`@`localhost` ;
-- CREATE USER `uyen.nguyenthitu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `uyen.nguyenthitu@gmail.com`@`localhost` ;
-- CREATE USER `khanh.nguyentrong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `khanh.nguyentrong@gmail.com`@`localhost` ;
-- CREATE USER `dam.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `dam.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `phuoc.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `phuoc.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `sang.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `sang.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `toan.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `toan.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `tuong.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tuong.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `anh.nguyenvutien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `anh.nguyenvutien@gmail.com`@`localhost` ;
-- CREATE USER `nguyen.nguyenxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `nguyen.nguyenxuan@gmail.com`@`localhost` ;
-- CREATE USER `hoang.ngyenthuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hoang.ngyenthuy@gmail.com`@`localhost` ;
-- CREATE USER `khoa.phamdinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `khoa.phamdinh@gmail.com`@`localhost` ;
-- CREATE USER `hoa.phamdotuyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hoa.phamdotuyet@gmail.com`@`localhost` ;
-- CREATE USER `nguyen.phamhole@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `nguyen.phamhole@gmail.com`@`localhost` ;
-- CREATE USER `thao.phamphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thao.phamphuong@gmail.com`@`localhost` ;
-- CREATE USER `vu.phamtan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `vu.phamtan@gmail.com`@`localhost` ;
-- CREATE USER `dung.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `dung.phamthi@gmail.com`@`localhost` ;
-- CREATE USER `thao.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thao.phamthi@gmail.com`@`localhost` ;
-- CREATE USER `hieu.phamthiminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hieu.phamthiminh@gmail.com`@`localhost` ;
-- CREATE USER `huyen.phamthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `huyen.phamthithanh@gmail.com`@`localhost` ;
-- CREATE USER `tam.phamthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tam.phamthithanh@gmail.com`@`localhost` ;
-- CREATE USER `an.phamthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `an.phamthithu@gmail.com`@`localhost` ;
-- CREATE USER `trang.phamthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `trang.phamthithuy@gmail.com`@`localhost` ;
-- CREATE USER `tuan.phananh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tuan.phananh@gmail.com`@`localhost` ;
-- CREATE USER `toan.phanchi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `toan.phanchi@gmail.com`@`localhost` ;
-- CREATE USER `chau.phanthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `chau.phanthimy@gmail.com`@`localhost` ;
-- CREATE USER `ha.phanthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ha.phanthingoc@gmail.com`@`localhost` ;
-- CREATE USER `chau.phanvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `chau.phanvan@gmail.com`@`localhost` ;
-- CREATE USER `ha.phanvokhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ha.phanvokhanh@gmail.com`@`localhost` ;
-- CREATE USER `nhut.thachminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `nhut.thachminh@gmail.com`@`localhost` ;
-- CREATE USER `soc.thachthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `soc.thachthi@gmail.com`@`localhost` ;
-- CREATE USER `thien.trandang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thien.trandang@gmail.com`@`localhost` ;
-- CREATE USER `toan.trankhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `toan.trankhanh@gmail.com`@`localhost` ;
-- CREATE USER `dang.tranmaikhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `dang.tranmaikhanh@gmail.com`@`localhost` ;
-- CREATE USER `nhut.tranminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `nhut.tranminh@gmail.com`@`localhost` ;
-- CREATE USER `anh.trannguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `anh.trannguyenminh@gmail.com`@`localhost` ;
-- CREATE USER `trung.trannguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `trung.trannguyenthanh@gmail.com`@`localhost` ;
-- CREATE USER `quang.tranthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `quang.tranthanh@gmail.com`@`localhost` ;
-- CREATE USER `hanh.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hanh.tranthi@gmail.com`@`localhost` ;
-- CREATE USER `oanh.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `oanh.tranthi@gmail.com`@`localhost` ;
-- CREATE USER `van.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `van.tranthi@gmail.com`@`localhost` ;
-- CREATE USER `nhung.tranthikieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `nhung.tranthikieu@gmail.com`@`localhost` ;
-- CREATE USER `anh.tranthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `anh.tranthikim@gmail.com`@`localhost` ;
-- CREATE USER `ha.tranthile@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ha.tranthile@gmail.com`@`localhost` ;
-- CREATE USER `nguyet.tranthiminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `nguyet.tranthiminh@gmail.com`@`localhost` ;
-- CREATE USER `thu.tranthinguyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thu.tranthinguyet@gmail.com`@`localhost` ;
-- CREATE USER `ha.tranthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ha.tranthithu@gmail.com`@`localhost` ;
-- CREATE USER `giang.trantruong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `giang.trantruong@gmail.com`@`localhost` ;
-- CREATE USER `mach.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `mach.tranvan@gmail.com`@`localhost` ;
-- CREATE USER `xuan.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `xuan.tranvan@gmail.com`@`localhost` ;
-- CREATE USER `chat.trinhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `chat.trinhthi@gmail.com`@`localhost` ;
-- CREATE USER `khuong.trinhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `khuong.trinhvan@gmail.com`@`localhost` ;
-- CREATE USER `trung.truonghoanhminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `trung.truonghoanhminh@gmail.com`@`localhost` ;
-- CREATE USER `khai.truongquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `khai.truongquang@gmail.com`@`localhost` ;
-- CREATE USER `an.truongvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `an.truongvan@gmail.com`@`localhost` ;
-- CREATE USER `hiep.truongvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hiep.truongvan@gmail.com`@`localhost` ;
-- CREATE USER `nhu.vanthihuynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `nhu.vanthihuynh@gmail.com`@`localhost` ;
-- CREATE USER `ngoc.vaybich@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ngoc.vaybich@gmail.com`@`localhost` ;
-- CREATE USER `duc.voanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `duc.voanh@gmail.com`@`localhost` ;
-- CREATE USER `duong.vodong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `duong.vodong@gmail.com`@`localhost` ;
-- CREATE USER `tri.vominh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tri.vominh@gmail.com`@`localhost` ;
-- CREATE USER `huy.voquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `huy.voquoc@gmail.com`@`localhost` ;
-- CREATE USER `linh.vothanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `linh.vothanh@gmail.com`@`localhost` ;
-- CREATE USER `huyen.vothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `huyen.vothi@gmail.com`@`localhost` ;
-- CREATE USER `phuoc.vothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `phuoc.vothi@gmail.com`@`localhost` ;
-- CREATE USER `yen.vothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `yen.vothi@gmail.com`@`localhost` ;
-- CREATE USER `ngoc.vothinhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `ngoc.vothinhu@gmail.com`@`localhost` ;
-- CREATE USER `hai.votuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hai.votuan@gmail.com`@`localhost` ;
-- CREATE USER `hau.vovan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hau.vovan@gmail.com`@`localhost` ;
-- CREATE USER `tam.vuduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tam.vuduy@gmail.com`@`localhost` ;
-- CREATE USER `anh.vuhung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `anh.vuhung@gmail.com`@`localhost` ;
-- CREATE USER `trieu.vuminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `trieu.vuminh@gmail.com`@`localhost` ;
-- CREATE USER `hang.vunguyenthuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hang.vunguyenthuy@gmail.com`@`localhost` ;
-- CREATE USER `chung.vuquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `chung.vuquoc@gmail.com`@`localhost` ;
-- CREATE USER `hoai.vuthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `hoai.vuthanh@gmail.com`@`localhost` ;
-- CREATE USER `thuan.vuthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thuan.vuthi@gmail.com`@`localhost` ;
-- CREATE USER `tu.vuthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `tu.vuthi@gmail.com`@`localhost` ;
-- CREATE USER `my.vuthiha@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `my.vuthiha@gmail.com`@`localhost` ;
-- CREATE USER `loan.vuthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `loan.vuthithanh@gmail.com`@`localhost` ;
-- CREATE USER `trang.vuthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `trang.vuthithuy@gmail.com`@`localhost` ;
-- CREATE USER `thang.vutien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `WorkerRole`@`localhost` TO `thang.vutien@gmail.com`@`localhost` ;

-- create designer account

CREATE USER `hung.bui@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `DesignerRole`@`localhost` TO `hung.bui@gmail.com`@`localhost` ;
CREATE USER `thiet.buidinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `DesignerRole`@`localhost` TO `thiet.buidinh@gmail.com`@`localhost` ;
-- CREATE USER `tuyen.buiduc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `tuyen.buiduc@gmail.com`@`localhost` ;
-- CREATE USER `kieu.buithikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `kieu.buithikim@gmail.com`@`localhost` ;
-- CREATE USER `dung.caovan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `dung.caovan@gmail.com`@`localhost` ;
-- CREATE USER `khoa.chauanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `khoa.chauanh@gmail.com`@`localhost` ;
-- CREATE USER `hanh.chauthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hanh.chauthi@gmail.com`@`localhost` ;
-- CREATE USER `duyen.chauthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `duyen.chauthihong@gmail.com`@`localhost` ;
-- CREATE USER `phi.cungkieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `phi.cungkieu@gmail.com`@`localhost` ;
-- CREATE USER `vui.dangcong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `vui.dangcong@gmail.com`@`localhost` ;
-- CREATE USER `cuong.danghung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `cuong.danghung@gmail.com`@`localhost` ;
-- CREATE USER `ba.dangthe@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `ba.dangthe@gmail.com`@`localhost` ;
-- CREATE USER `tien.dangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `tien.dangvan@gmail.com`@`localhost` ;
-- CREATE USER `son.daohoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `son.daohoang@gmail.com`@`localhost` ;
-- CREATE USER `khanh.daoquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `khanh.daoquang@gmail.com`@`localhost` ;
-- CREATE USER `thuong.dinhhoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `thuong.dinhhoai@gmail.com`@`localhost` ;
-- CREATE USER `luyen.dinhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `luyen.dinhthi@gmail.com`@`localhost` ;
-- CREATE USER `huy.dothaianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `huy.dothaianh@gmail.com`@`localhost` ;
-- CREATE USER `thanh.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `thanh.dothi@gmail.com`@`localhost` ;
-- CREATE USER `huyen.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `huyen.dothi@gmail.com`@`localhost` ;
-- CREATE USER `mai.dothihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `mai.dothihong@gmail.com`@`localhost` ;
-- CREATE USER `lich.dovan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `lich.dovan@gmail.com`@`localhost` ;
-- CREATE USER `cuong.duonghung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `cuong.duonghung@gmail.com`@`localhost` ;
-- CREATE USER `duyen.hathihai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `duyen.hathihai@gmail.com`@`localhost` ;
-- CREATE USER `tien.hoangthicam@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `tien.hoangthicam@gmail.com`@`localhost` ;
-- CREATE USER `cuong.hoangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `cuong.hoangvan@gmail.com`@`localhost` ;
-- CREATE USER `thu.huynhthicam@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `thu.huynhthicam@gmail.com`@`localhost` ;
-- CREATE USER `oanh.huynhthikieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `oanh.huynhthikieu@gmail.com`@`localhost` ;
-- CREATE USER `phung.huynhthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `phung.huynhthikim@gmail.com`@`localhost` ;
-- CREATE USER `dung.huynhthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `dung.huynhthimy@gmail.com`@`localhost` ;
-- CREATE USER `hau.huynhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hau.huynhvan@gmail.com`@`localhost` ;
-- CREATE USER `oanh.lamnhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `oanh.lamnhu@gmail.com`@`localhost` ;
-- CREATE USER `thien.ledinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `thien.ledinh@gmail.com`@`localhost` ;
-- CREATE USER `que.ledong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `que.ledong@gmail.com`@`localhost` ;
-- CREATE USER `truc.leminhphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `truc.leminhphuong@gmail.com`@`localhost` ;
-- CREATE USER `loc.lephat@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `loc.lephat@gmail.com`@`localhost` ;
-- CREATE USER `si.lethihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `si.lethihoang@gmail.com`@`localhost` ;
-- CREATE USER `lieu.lethihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `lieu.lethihong@gmail.com`@`localhost` ;
-- CREATE USER `truc.lethithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `truc.lethithanh@gmail.com`@`localhost` ;
-- CREATE USER `phuc.luonghuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `phuc.luonghuu@gmail.com`@`localhost` ;
-- CREATE USER `dien.luongquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `dien.luongquang@gmail.com`@`localhost` ;
-- CREATE USER `van.lythi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `van.lythi@gmail.com`@`localhost` ;
-- CREATE USER `nhan.ngohoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `nhan.ngohoai@gmail.com`@`localhost` ;
-- CREATE USER `hung.ngoquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hung.ngoquang@gmail.com`@`localhost` ;
-- CREATE USER `khoa.ngoquangdang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `khoa.ngoquangdang@gmail.com`@`localhost` ;
-- CREATE USER `sang.ngothikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `sang.ngothikim@gmail.com`@`localhost` ;
-- CREATE USER `son.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `son.nguyen@gmail.com`@`localhost` ;
-- CREATE USER `anh.nguyendinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `anh.nguyendinh@gmail.com`@`localhost` ;
-- CREATE USER `tan.nguyendoan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `tan.nguyendoan@gmail.com`@`localhost` ;
-- CREATE USER `ngan.nguyenhoaithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `ngan.nguyenhoaithanh@gmail.com`@`localhost` ;
-- CREATE USER `dien.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `dien.nguyenhoang@gmail.com`@`localhost` ;
-- CREATE USER `long.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `long.nguyenhoang@gmail.com`@`localhost` ;
-- CREATE USER `thuan.nguyenhoanggia@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `thuan.nguyenhoanggia@gmail.com`@`localhost` ;
-- CREATE USER `sinh.nguyenhung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `sinh.nguyenhung@gmail.com`@`localhost` ;
-- CREATE USER `nhu.nguyenhuynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `nhu.nguyenhuynh@gmail.com`@`localhost` ;
-- CREATE USER `dieu.nguyenhuynhhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `dieu.nguyenhuynhhong@gmail.com`@`localhost` ;
-- CREATE USER `anh.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `anh.nguyenngoc@gmail.com`@`localhost` ;
-- CREATE USER `khanh.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `khanh.nguyenngoc@gmail.com`@`localhost` ;
-- CREATE USER `long.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `long.nguyenngoc@gmail.com`@`localhost` ;
-- CREATE USER `nhi.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `nhi.nguyenngoc@gmail.com`@`localhost` ;
-- CREATE USER `anh.nguyenngochoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `anh.nguyenngochoang@gmail.com`@`localhost` ;
-- CREATE USER `nguyen.nguyenngockhoi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `nguyen.nguyenngockhoi@gmail.com`@`localhost` ;
-- CREATE USER `tam.nguyenngocthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `tam.nguyenngocthanh@gmail.com`@`localhost` ;
-- CREATE USER `son.nguyenphuoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `son.nguyenphuoc@gmail.com`@`localhost` ;
-- CREATE USER `phi.nguyenphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `phi.nguyenphuong@gmail.com`@`localhost` ;
-- CREATE USER `duy.nguyenquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `duy.nguyenquang@gmail.com`@`localhost` ;
-- CREATE USER `huy.nguyenquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `huy.nguyenquang@gmail.com`@`localhost` ;
-- CREATE USER `dat.nguyenquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `dat.nguyenquoc@gmail.com`@`localhost` ;
-- CREATE USER `to.nguyentan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `to.nguyentan@gmail.com`@`localhost` ;
-- CREATE USER `hoang.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hoang.nguyenthanh@gmail.com`@`localhost` ;
-- CREATE USER `phong.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `phong.nguyenthanh@gmail.com`@`localhost` ;
-- CREATE USER `huyen.nguyenthao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `huyen.nguyenthao@gmail.com`@`localhost` ;
-- CREATE USER `hang.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hang.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `hue.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hue.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `luyen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `luyen.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `nga.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `nga.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `ninh.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `ninh.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `phuong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `phuong.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `quyen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `quyen.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `thao.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `thao.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `thuong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `thuong.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `yen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `yen.nguyenthi@gmail.com`@`localhost` ;
-- CREATE USER `thu.nguyenthianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `thu.nguyenthianh@gmail.com`@`localhost` ;
-- CREATE USER `yen.nguyenthihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `yen.nguyenthihoang@gmail.com`@`localhost` ;
-- CREATE USER `hoang.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hoang.nguyenthikim@gmail.com`@`localhost` ;
-- CREATE USER `thoa.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `thoa.nguyenthikim@gmail.com`@`localhost` ;
-- CREATE USER `suong.nguyenthimai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `suong.nguyenthimai@gmail.com`@`localhost` ;
-- CREATE USER `hanh.nguyenthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hanh.nguyenthimy@gmail.com`@`localhost` ;
-- CREATE USER `khuyen.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `khuyen.nguyenthingoc@gmail.com`@`localhost` ;
-- CREATE USER `binh.nguyenthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `binh.nguyenthithanh@gmail.com`@`localhost` ;
-- CREATE USER `duong.nguyenthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `duong.nguyenthithuy@gmail.com`@`localhost` ;
-- CREATE USER `anh.nguyenthitram@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `anh.nguyenthitram@gmail.com`@`localhost` ;
-- CREATE USER `hoang.nguyenthuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hoang.nguyenthuy@gmail.com`@`localhost` ;
-- CREATE USER `hieu.nguyentrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hieu.nguyentrung@gmail.com`@`localhost` ;
-- CREATE USER `tien.nguyentrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `tien.nguyentrung@gmail.com`@`localhost` ;
-- CREATE USER `linh.nguyentuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `linh.nguyentuan@gmail.com`@`localhost` ;
-- CREATE USER `dau.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `dau.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `hau.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hau.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `long.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `long.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `ngon.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `ngon.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `son.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `son.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `trang.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `trang.nguyenvan@gmail.com`@`localhost` ;
-- CREATE USER `quang.nguyenvinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `quang.nguyenvinh@gmail.com`@`localhost` ;
-- CREATE USER `nhan.nguyenvy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `nhan.nguyenvy@gmail.com`@`localhost` ;
-- CREATE USER `phuc.phamhoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `phuc.phamhoai@gmail.com`@`localhost` ;
-- CREATE USER `phuoc.phamhuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `phuoc.phamhuu@gmail.com`@`localhost` ;
-- CREATE USER `khanh.phamphu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `khanh.phamphu@gmail.com`@`localhost` ;
-- CREATE USER `tien.phamphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `tien.phamphuong@gmail.com`@`localhost` ;
-- CREATE USER `kieu.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `kieu.phamthi@gmail.com`@`localhost` ;
-- CREATE USER `huyen.phamthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `huyen.phamthimy@gmail.com`@`localhost` ;
-- CREATE USER `ngoc.phamtien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `ngoc.phamtien@gmail.com`@`localhost` ;
-- CREATE USER `nghia.phamtrong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `nghia.phamtrong@gmail.com`@`localhost` ;
-- CREATE USER `hien.phamvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hien.phamvan@gmail.com`@`localhost` ;
-- CREATE USER `nghia.phamxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `nghia.phamxuan@gmail.com`@`localhost` ;
-- CREATE USER `my.phanhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `my.phanhoang@gmail.com`@`localhost` ;
-- CREATE USER `hien.phannguyenphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hien.phannguyenphuong@gmail.com`@`localhost` ;
-- CREATE USER `nguyen.phanthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `nguyen.phanthanh@gmail.com`@`localhost` ;
-- CREATE USER `ngoc.phanthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `ngoc.phanthi@gmail.com`@`localhost` ;
-- CREATE USER `no.phanthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `no.phanthi@gmail.com`@`localhost` ;
-- CREATE USER `vien.phungduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `vien.phungduy@gmail.com`@`localhost` ;
-- CREATE USER `sen.son@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `sen.son@gmail.com`@`localhost` ;
-- CREATE USER `lan.tathi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `lan.tathi@gmail.com`@`localhost` ;
-- CREATE USER `uyen.tothihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `uyen.tothihong@gmail.com`@`localhost` ;
-- CREATE USER `nhi.trananh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `nhi.trananh@gmail.com`@`localhost` ;
-- CREATE USER `hoa.tranquynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hoa.tranquynh@gmail.com`@`localhost` ;
-- CREATE USER `minh.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `minh.tranthi@gmail.com`@`localhost` ;
-- CREATE USER `te.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `te.tranthi@gmail.com`@`localhost` ;
-- CREATE USER `chau.tranthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `chau.tranthihong@gmail.com`@`localhost` ;
-- CREATE USER `tam.tranthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `tam.tranthithanh@gmail.com`@`localhost` ;
-- CREATE USER `hoa.tranthithuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hoa.tranthithuan@gmail.com`@`localhost` ;
-- CREATE USER `trinh.tranthivan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `trinh.tranthivan@gmail.com`@`localhost` ;
-- CREATE USER `tuyen.tranthien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `tuyen.tranthien@gmail.com`@`localhost` ;
-- CREATE USER `hua.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `hua.tranvan@gmail.com`@`localhost` ;
-- CREATE USER `song.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `song.tranvan@gmail.com`@`localhost` ;
-- CREATE USER `oanh.tranxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `oanh.tranxuan@gmail.com`@`localhost` ;
-- CREATE USER `nhi.trinhthiphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `nhi.trinhthiphuong@gmail.com`@`localhost` ;
-- CREATE USER `tuan.truongminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `tuan.truongminh@gmail.com`@`localhost` ;
-- CREATE USER `viet.truongquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `viet.truongquang@gmail.com`@`localhost` ;
-- CREATE USER `su.truongthiminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
-- GRANT `DesignerRole` TO `su.truongthiminh@gmail.com`@`localhost` ;

